---
- name: Provision Web Servers
  hosts: tag_name_nginx
  become: true
  tasks:
    - name: Install pip3
      apt:
        update_cache: yes
        name: python3-pip
          
    - name: Install docker
      apt:
        name: docker.io

    - name: Install python docker sdk
      shell: pip3 install docker
          
    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true
      
    - name: Login into DockerHub
      docker_login: 
        username: ajwpak
        password: "{{ DOCKER_PWD }}"

    - name: Run Image
      shell: docker run --name nginx-static -dit -p 80:80 -p 443:443 ajwpak/nginx-static

    - name: Logout of DockerHub
      docker_login:
        state: absent